# Config file for Air

# Working directory
root = "."

# Temp folder to store built binary
tmp_dir = "tmp"

# Binary file name (will be rebuilt by Air)
bin = "app"

# Watch .go files only (ignores others like README, etc.)
include_ext = ["go", "tpl", "tmpl", "html"]

# Exclude folders from watching
exclude_dir = ["tmp", "vendor", "node_modules", ".git", "build"]

# Watch all files recursively under root
include = ["**/*.go"]

# Commands
[build]
cmd = "go build -o tmp/app main.go"
bin = "tmp/app"
delay = 1000 # milliseconds
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
exclude_regex = ["_test.go"]
follow_symlink = false
kill_delay = "2s"
log = "build.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
